### ISSUE TITLE
Batch creation of glycan using GlyTouCan IDs

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glyTableMaker-backend#103]
Replace the addition of glycans using single GlyTouCan ID with a batch option. Replace the input field with a text field that allows multiple GlyTouCan IDs (space or line break separated) to be entered. The new dialog also needs tag options. User should see a summary of how many IDs were accepted and added and how many of the IDs (and which one's) are invalid.

**Comment by senaarpinar** [comment]
I've added this feature as a new file download option.
