### ISSUE TITLE
Change new tag default message

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glyTableMaker-backend#105]
When adding a tag you can select from a dropdown or enter a new one. For the latter the message is "Enter tag and click Add". There is no add on the dialog. In the file upload its the "Submit" button and on other dialogs OK button. Change to "Enter new tag name".

**Comment by senaarpinar** [comment]
"Add" button exists when adding a tag through Glycan/Glycoprotein tables. But removed "click Add" part when accessed from other components.
