### ISSUE TITLE
Multiselection of same protein

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glyTableMaker-backend#111]
Raja create two version of the same protein, both with the same name:
* Version one without glycan
* Version two with glycan

When trying to add the protein to a collection (Add Glycoprotein) independent which one is clicked both get selected or deselected. But always the first gets added to collection. I suspect we are using protein ID, protein name or user given name for the selection. But none of them is unique (although we could talk about it for user given name).

**Comment by senaarpinar** [comment]
We are not allowing duplicate glycoproteins with the same name, anymore. This should be prevented now. I also changed the unique value in the table to the "id" ( internal id) of the protein.
