### ISSUE TITLE
GlyGen metadata - Evidence using DOID

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glyTableMaker-backend#112]
In the tooltip we should provide example which format we support for DOID. We also need to make sure that we can retrieve the paper information using the DOID formats supported.

**Comment by senaarpinar** [comment]
Look for an API to access the publication with DOID

**Comment by senaarpinar** [comment]
we can access the publication details with the given document URL  (eg. https://doi.org/10.3390/cimb45110575) and setting the accept header as "application/vnd.citationstyles.csl+json"
