### ISSUE TITLE
Database structure

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glyTableMaker-backend#13]
**Glycan table**
* Internal ID
* GlyTouCan ID
* WURCS
* GlycoCT (Optional)
* GWS (Optional)
* Mass
* Date/time added
* Newly registered?
* User ID

Where do we store the images?

**Collection table**
* ID
* Name
* Description
* User ID

**Collection/glycan table**
* m-to-n table
* date/time glycan was added

**Data type table**
* ID
* URI
* Name
* Description
* namespace

**Metadata table**
* ID
* Data type
* Collection 
* value

**Data type category table**
* ID
* Name
* Description

**Data type category/Data type table**
* m-to-n table

Put an ERD and dump into the repository.

**Comment by senaarpinar** [comment]
<img width="2027" alt="Screen Shot 2024-01-04 at 3 14 54 PM" src="https://github.com/glygener/glyTableMaker-backend/assets/8181316/233b14c7-6c03-4049-ba3b-2ef28ecc2911">

**Comment by senaarpinar** [comment]
![erdiagram](https://github.com/glygener/glyTableMaker-backend/assets/8181316/b364901c-e0b2-4405-b0fe-edc8be4186b4)

**Comment by senaarpinar** [comment]
Made some changes to collections table:

![erdiagram2](https://github.com/glygener/glyTableMaker-backend/assets/8181316/d06cb4a8-a6df-4367-9d06-7a8aa6f20c77)

**Comment by ReneRanzinger** [comment]
Can you please make them in higher resolution. Its really hard to read.

**Comment by senaarpinar** [comment]
I was using DBvisualizer's export to save it as an image but the resolution is not good. This is a screenshot. Please let me know if this is good.

<img width="1112" alt="Screen Shot 2024-03-05 at 11 38 45 AM" src="https://github.com/glygener/glyTableMaker-backend/assets/8181316/35a2d893-e774-40fe-9c99-f3af39ab2365">

**Comment by senaarpinar** [comment]
This is the latest with the addition of tags and upload errors:

<img width="953" alt="Screen Shot 2024-03-12 at 2 36 42 PM" src="https://github.com/glygener/glyTableMaker-backend/assets/8181316/689dc1c6-4daf-4c6a-b08b-98b954e96332">

**Comment by senaarpinar** [comment]
Latest with metadata and table maker templates etc.

<img width="1901" alt="ERDiagram" src="https://github.com/glygener/glyTableMaker-backend/assets/8181316/053f01fc-29a2-4eae-be5e-235eee2f8f77">
