### ISSUE TITLE
Glycan page

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glyTableMaker-backend#15]
Accessible from the Left side menu (#14).

* Add new GlyCan button. This triggers a dropdown
   * Sequence
   * Composition
   * Draw glycan
* Add glycans from file
* Glycan table with pagination controls
   * GlyTouCan ID (Link to GlyTouCan)
   * Status (pending registration, error, newly registered) for the first two the information field is accessible
   * Image
   * Mass
   * #collections
   * Information (empty by default otherwise an clickable icon is shown that shows the Hashcode for pending registration or error information for error)
   * Action column with delete icon. Will trigger a warning if glycan is part of collections and confirm that it should be removed from the collections (yes/no)

**Comment by senaarpinar** [comment]
* add another option to the add glycan dropdown:
  * Glytoucan ID

**Comment by senaarpinar** [comment]
implemented the basics. 
filtering still needs to be implemented in backend
and information column remains to be implemented
