### ISSUE TITLE
Reset of error message

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glyTableMaker-backend#18]
On the forgot password page I triggered an error with a wrong email and afterwards entered the right one. Now it shows both message. It did not reset the error message. 
![Screenshot_20231204_233327](https://github.com/glygener/glyTableMaker-backend/assets/2267640/97fb3148-6697-4b85-a0e2-78cbc9e30ba7)

That might be true for other pages/dialogs as well.

Strangely enough the green box seems to have spacing to the input field (see #17)

**Comment by senaarpinar** [comment]
done
