### ISSUE TITLE
Reset password -> change password

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glyTableMaker-backend#20]
Reseting the password should force a password change and autologout afterwards.

**Comment by senaarpinar** [comment]
@ReneRanzinger can you explain this a little? Are you suggesting to change the process where we send an email to the user (with the new password)?

**Comment by ReneRanzinger** [comment]
@senaarpinar I think its common to force the creation of a new password by the user when password reset. Either you get send a temporary password that allows you to login but forces you immediately to create a new password. Or you get a reset token that does the same thing (getting you to a page to enter the new password twice). Hope that makes sense.

**Comment by senaarpinar** [comment]
Our current implementation sends a temporary password through email. So once the user uses that temporary password to login, s/he needs to be forced to the changePassword page to create a new password. Is that correct?

**Comment by ReneRanzinger** [comment]
Yes. In other systems we had a flag in the user table to indicate it. If the flag was set the user would be forced to the change password page, otherwise he continues normal. From the forced changed password page you are logged out and are back at the login page.

**Comment by senaarpinar** [comment]
do we always log out and back to login page after password change? or only for this specific case?

**Comment by ReneRanzinger** [comment]
Only this case.
