### ISSUE TITLE
Center not center

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glyTableMaker-backend#23]
On a large screen the content in the center of the page (e.g. login etc.) looks centered. But as soon as the window gets smaller the left side shrinks more than the right side.

![Screenshot from 2024-01-09 13-45-33](https://github.com/glygener/glyTableMaker-backend/assets/2267640/8a3a4095-c81a-4ff9-9e8d-881d974b960f)

**Comment by senaarpinar** [comment]
fixed
