### ISSUE TITLE
Edit profile page - Submit button is disabled after remove optional content

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glyTableMaker-backend#24]
* Create an account with group, department, organization and website filled
* Login -> Profile
* Edit profile
* Remove group name (empty field)

If you use backspace the submit button is enabled till the last character is removed. After this is stays disabled. Since the fields are optional its valid to remove the content. That is different for the name fields.

**Comment by senaarpinar** [comment]
fixed
