### ISSUE TITLE
Reset password page - tab issue

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glyTableMaker-backend#28]
* Use forgot password
* receive new password and login
* it forces you to change the password
* click into the "New Password" field
* Tab => "Confirm password"
* Tab => Some strange hidden widget
* Tab => Cancel button

What is that thing between "Confirm password" and "cancel button"?

**Comment by senaarpinar** [comment]
removed the extra control before the button. This was done in several pages.
