### ISSUE TITLE
Collection page

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glyTableMaker-backend#29]
Collection page is accessible from the Left side menu (#14). 
* Add collection button (see below)
* Table with the user owned collections
   * Collection Name
   * Mouse over icon with Description (can follow after the name or in own column)
   * Number of glycans
   * Number of metadata columns
   * Action column (Edit, Delete)

Add or Edit collection
* Name field (unique per user)
* Description text box
* "Save general information" button
* Add glycan button
* Table with the glycans in the collection
   * "Standard" glycan columns
* Add metadata button
* Table with metadata information
  * Data type name
  * Data type description logo (as icon after name or own column)
  * Value column
  * Action column (Edit, Delete)
* Save metadata button

Add or Edit metadata (Dialog)
* Choose Data Type button ==> Hierachy view of category left and selected category node associated datatypes right + OK/Cancel button ; Needs to make sure Datatype is unique per collection
* Input field for value
* OK/Cancel button

**Comment by senaarpinar** [comment]
collections table and add general information for a collection part has been implemented

**Comment by senaarpinar** [comment]
implemented adding/removing glycans to/from the collection

**Comment by senaarpinar** [comment]
created a new ticket for the metadata part #47 
other parts have been implemented
