### ISSUE TITLE
Add Glycan by composition

### ISSUE THREAD

**Issue by senaarpinar** [glygener/glyTableMaker-backend#32]
We need to have a composition selector similar to https://gnome.glyomics.org/restrictions/GlyGen.StructureBrowser.html

**Comment by senaarpinar** [comment]
I cannot build the latest version on the server but implemented the following for entering the compositions. 
@ReneRanzinger any suggestions?

<img width="754" alt="Screen Shot 2024-02-06 at 2 21 10 PM" src="https://github.com/glygener/glyTableMaker-backend/assets/8181316/273a6789-b59f-4cf9-ae62-2954621482e5">

**Comment by ReneRanzinger** [comment]
For now this is fine. We will have to think about better solution for the half square and half diamonds. It would also be good to have a readable composition string on the page that gets updated with the button clicks. What are you sending to the server when the "Add Glycan" button is clicked?

**Comment by senaarpinar** [comment]
I added the composition string on the page
