### ISSUE TITLE
Glycan page - information column

### ISSUE THREAD

**Issue by senaarpinar** [glygener/glyTableMaker-backend#34]
Information column needs to show glytoucan hash or error if any.
@ReneRanzinger, the material-react-table provides a mechanism to show additional details for each row (expanding the row), should we use that functionality for displaying this information.

See an example: https://www.material-react-table.com/docs/examples/advanced (first column with the arrows)

or I can add an icon to open the information dialog as you previously suggested

**Comment by ReneRanzinger** [comment]
@senaarpinar 
I like the idea but:
* can we make a column that has the opening symbol only if hashcode or error is there?
* can this be a later column and not the first?
* Can we replace the opening symbol with an own icon? Error or information icon?

**Comment by senaarpinar** [comment]
* can we make a column that has the opening symbol only if hashcode or error is there?
  * yes, we can disable when there is no additional information
* can this be a later column and not the first?
  * as far as I can see, it can be the first or the last column, not in between. Need to see if it can be placed before action column
* Can we replace the opening symbol with an own icon? Error or information icon?
  * yes, we can change the icon

**Comment by senaarpinar** [comment]
@ReneRanzinger I tested this a little. We can only place it as the last icon so it will go after actions column. Not sure if we can change the column header (it either has >> to expand or "Expand" as the header). Also, although it shows in the examples that it can be disabled, it didn't work for me.

**Comment by senaarpinar** [comment]
added an "info" icon to open up a modal dialog to show the registration info/errors.
