### ISSUE TITLE
Strange error message when filtering

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glyTableMaker-backend#37]
* I added a single Glycan by ID.
* Selected the filter option for "Status"
* Hide "Status"
* Show all columns
* Filter status by "a" => "Error lading data"

![Screenshot from 2024-01-30 18-12-34](https://github.com/glygener/glyTableMaker-backend/assets/2267640/ef88bd74-7eab-401b-8216-5ae36b8bec97)

**Comment by senaarpinar** [comment]
@ReneRanzinger Filtering has not yet been implemented fully on the backend. I should have created a new ticket for that.

**Comment by senaarpinar** [comment]
implemented the filtering. this should not happen. Also disabled filtering for status and collections columns.
