### ISSUE TITLE
Sign up to crowded

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glyTableMaker-backend#4]
The current sign up dialog is too crowded. Make it a multistage wizard with all input field taking full width (similar to login page):
**First page**
* First name
* Last name
* Email
There is only a next button in the right half of the dialog below the fields.

**Second page**
* Username
* 2x password
There is a next and back button on this page that are on the same height. There is also the centered "Sign Up" button below them. If this button is clicked it assumes page 3 information is empty.

** Third page**
* Group name
* Department
* Organization
* Website
There is only a back button in the left half of the dialog below the fields. There is a centered "Sign Up" button below.

Similar to the login page have vertical spacing between the text fields.

**Comment by senaarpinar** [comment]
This is the version, with changes similar to the Profile page. @ReneRanzinger Do you still think we need to divide into 3 pages?
<img width="736" alt="Screen Shot 2023-12-15 at 2 18 07 PM" src="https://github.com/glygener/glyTableMaker-backend/assets/8181316/b132d594-7cfc-49c6-8660-0e275c3856f8">
