### ISSUE TITLE
SQL fields to small

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glyTableMaker-backend#42]
![Screenshot from 2024-01-30 19-25-50](https://github.com/glygener/glyTableMaker-backend/assets/2267640/b670d914-64c7-4120-9db2-9a27aaceea64)

**Comment by senaarpinar** [comment]
changed glycan sequence columns to text. @ReneRanzinger what about metadata values. if we make them text, are they going to be searchable?

**Comment by ReneRanzinger** [comment]
There are two types of metadata values:
* Free text
* Dictionary controlled

For the later we would need:
* Dictionary
* ID
* Display name

For the last we could reuse the text field for the free text input.

**Comment by senaarpinar** [comment]
done
