### ISSUE TITLE
Add glycan from file

### ISSUE THREAD

**Issue by senaarpinar** [glygener/glyTableMaker-backend#43]
Allow adding glycans from a GWS file. @ReneRanzinger  Do we need to allow any other file types? 
Backend: Need to implement the web service as an asynchronous web service.
Frontend: Need to implement a mechanism to show the status/errors of latest upload.

**Comment by ReneRanzinger** [comment]
@ReneRanzinger We should forsee a dropdown for file format but right now GWS would be the only entry there.

**Comment by senaarpinar** [comment]
implemented. may need to revisit error display
