### ISSUE TITLE
Usage of uploads

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glyTableMaker-backend#44]
How are the following fields used in this table:
* error
* message

Does any of them store the (GWS) sequence that failed?

What is `accessddate` used for?

**Comment by senaarpinar** [comment]
"message" contains the summary of the upload like "3 out of 5 glycans have been added"
"error" is currently a string but I am planning to make it an object (json) and store the file contents there, or add another field for the file contents. I have not decided on the data structure yet.
"accessedDate" is used to mark if the errors of this upload has been viewed. If the user marks it as viewed, it is not shown to the user again.

**Comment by senaarpinar** [comment]
closing
