### ISSUE TITLE
Adding glycans to collections based on file

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glyTableMaker-backend#45]
What would be the easiest way to add glycans to a collection based on a file?

User creates a new GWS file for an dataset. Uploads GWS. GWS file gets processed. Now he wants to add all the structures to a new collection. Also keep in mind that upload date might not help if a glycan was uploaded as part of another GWS in an earlier dataset.

**Comment by senaarpinar** [comment]
@ReneRanzinger Are we going to use "keywords" field to be able to achieve this?

**Comment by ReneRanzinger** [comment]
Yes, that is what we decided. See #48.
