### ISSUE TITLE
Dictionaries/namespaces to add

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glyTableMaker-backend#46]
* [NCBI Taxonomy](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi) - [Download site](https://ftp.ncbi.nih.gov/pub/taxonomy/)
* [UBERON](https://www.ebi.ac.uk/ols4/ontologies/uberon) - [Download site](https://uberon.github.io/downloads.html)
* [Cellosaurus](https://www.cellosaurus.org/) - [Download site](https://ftp.expasy.org/databases/cellosaurus/)
* [Human Disease Ontology](https://www.ebi.ac.uk/ols4/ontologies/doid) - [Download site](https://disease-ontology.org/downloads/)
* GlyGen Experimental method
   * MS 
   * MS/MS 
   * LC-MS/MS 
   * LC-MS 
   * CE-MS 
   * CE-MS/MS 
   * CE 
   * HPLC 
   * GC 
   * GC-MS 
* [Human Phenotype Ontology](https://hpo.jax.org/app/)
* GlyGen functional annotation
   * adhesion 
   * homing 
   * inflammation 
   * protein targeting 
   * protein secretion 
   * protein stability 
   * protein folding 
   * ER stress 
   * protein degradation 
   * circulating half-life 
   * clearance 
   * internalization 
   * metastasis 
   * shielding 
   * recognition 
   * toxin receptor 
   * viral receptor 
   * microbial receptor 
   * receptor signaling 
   * sperm maturation 
   * biomarker 
   * differentiation

**Comment by senaarpinar** [comment]
done
