### ISSUE TITLE
Glycan File upload changes

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glyTableMaker-backend#50]
Change the uploads table to glycan_file_upload
* glycan_file_upload_id
* accesseddate
* startdate
* status
* userid
* filename
* format

Add new table glycan_file_errors
* primary ID
* position (position in the file)
* error message
* glycan_file_upload_id (FK to glycan_file_upload)
* sequence

Add an n-to-m table between glycans and glycan_file_upload

**Blocker for:**
* #51
* #52

**Comment by senaarpinar** [comment]
done
