### ISSUE TITLE
File upload mechanism

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glyTableMaker-backend#51]
If a glycan file (GWS) is uploaded:
* create new entry in glycan_file_upload and store the original file name in the table. 
* store the original file in a none-accessible folder using the ID from glycan_file_upload_id as filename. 
* load the sequence and parse them
  * if successful put them into glycan table and add an entry in the m-to-n between glycan and glycan_file_upload
  * if failed add an entry in the glycan_file_error table with the sequence that failed and the error message

**Dependency:**
* #50 

**Blocker for:**
* #52

**Comment by senaarpinar** [comment]
@ReneRanzinger if the glycan is a duplicate, we ignore it.  But we still need to add an entry in the m-to-n between the glycan and glycan_file_upload for the existing glycan and this upload, right?

**Comment by ReneRanzinger** [comment]
Yes. That glycan also needs to get the tags assigned.
