### ISSUE TITLE
Glycan File upload control

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glyTableMaker-backend#52]
On the Glycans page have another button right aligned besides the two add button. "File upload" it would be good if it has a "unread messages" marker if there are uploads with errors. Or the button could have a different color.

When clicking the button: Go to a new page with a table and a back button. The table has the following columns:
* File upload date
* Original file name
* Number of glycans (that are in the glycan table)
* Number of errors (that are in the glycan_file_errors table)
* Action (Delete, Add Tag, Show errors)

1. Delete will remove the entry in glycan_file_upload and corresponding entries in glycan_file_errors table but not in glycan table.
2. Add tag opens a dialog allowing to add an additional tag to all glycans that are associated with the submission.
3. Show errors opens a dialog with the table of errors. 
   * position
   * sequence
   * error message
   * action (report)

Reporting the error sends an email to us and a copy to the user. Opening the errors dialog marks the file upload as "read" and will no longer trigger the "unread messages" marker.

**Dependencies**
* #50 
* #51

**Comment by senaarpinar** [comment]
@ReneRanzinger In your description above:
1. Delete will remove the entry in glycan_file_upload and corresponding entries in glycan_file_errors table but not in glycan table.
      How are we supposed to delete the file uploads but keep them in the glycan table? Glycan table has a reference to the 
      glycan_file_upload table.

**Comment by senaarpinar** [comment]
done
