### ISSUE TITLE
Add tag to glycan

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glyTableMaker-backend#53]
The following dialog can be triggered by:
* new action in glycans table
* by action in glycan file submission table (see #52)

**Dialog**
* Title: Add tag
* Content:
  * Radio button group for dropdown with existing user defined tags (only this user) or new tag (text field)
  * Add and cancel button

If a new tag is added check if its already exist. If not add it and assign it to the corresponding glycans. The user might select a tag the glycan already has, in this case ignore the assignment. No error message needed.

**Dependency:**
* #48

**Comment by senaarpinar** [comment]
implemented
