### ISSUE TITLE
Validators for namespaces

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glyTableMaker-backend#55]
For the namespaces in #54 we need validators classes that take a user input and confirm it fits the namespace. If the namespace has a URI it needs to be checked against the dictionary. If the namespace has no URI a costume logic based on the type needs to be implemented.

**Comment by senaarpinar** [comment]
@ReneRanzinger can you provide the list for BCO contributor options/format?

**Comment by ReneRanzinger** [comment]
You can find the information [here](https://github.com/glygener/glygen-issues/issues/42#issuecomment-1710448710)

**Comment by senaarpinar** [comment]
done
