### ISSUE TITLE
Error Information for failed structures

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glyTableMaker-backend#58]
This error message is not really helpful. 

![error](https://github.com/glygener/glyTableMaker-backend/assets/2267640/52ad6e65-cca5-42c1-8df7-c25ecbe4005c)

Can we show more details with an "More details" option? Also a OK button should be there.

**Comment by senaarpinar** [comment]
This particular problem was in our code. We were sending null for the sequence to the registration API. The error we are getting is not very informative (internal server error) but I still added the code to parse the error and show the message to the user. In this case, Glytoucan API is sending an error back and not assigning a hash for the submission.

@ReneRanzinger 
I am still investigating how to get the errors after we get a glytoucan hash after registration. If the structure was invalid for example, there will be no accession number but we get hash and some kind of validation error probably later on. 
I checked the API calls mentioned [here](https://github.com/glygener/glygen-array-backend/issues/89). I tested sending an invalid sequence but none of the listed APIs is giving an error information about this submission.
Example hash: 6407df5cefbbd62860b9f762158657f1663d51423e25d85e1293a903c0681031

**Comment by senaarpinar** [comment]
added OK button

**Comment by senaarpinar** [comment]
added errorJson to Glycans to store the actual error response. 
also used https://sparqlist.glycosmos.org/sparqlist/gtc_repo_usub_by_hashkey to check the status of submission using the hash key. In case of an error, the glycan's status is updated to "Error".
