### ISSUE TITLE
Google sign in not working

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glyTableMaker-backend#6]
When clicking the button an empty page pops up.

**Comment by senaarpinar** [comment]
Google login is now working on the server.

There were some routing issues on the server that prevented routing to "oauth/redirect" page on the server. Had to add the full URL to the homepage (in package.json) to be able to use paths similar to the above (with subfolders) for the router. 
Need to investigate further why this (homepage was set to ".") was not necessary before (earlier react/react-router versions) but necessary now.
