### ISSUE TITLE
Table Maker

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glyTableMaker-backend#62]
When clicking on the Table Maker option in the left side menu open a page:

**Headline:** 
Create table

**Section 1**
* "Create table for:"
* 2 divs/span/cells side by side 
  * left side: 
    * bullet point list with collections
    * needs to be nested if collections of collections are added
    * for each collection the name and delete icon are shown
  * right side:
    * Add collection button
    * Add collections of collections button

**Section 2**
* "with columns:"
* In the next line "Use template" dropdown with templates and "Apply" button. The apply button will fill the following table with the information from the template.
* Table with the column definitions preferable with up/down arrows to change order and an add button (#63)
  * "Column number"
  * "Name"
  * "Metadata" (can be empty)
  * "Type" (can be empty)
  * Delete icon
* Button "Save as template"
  * Dialog with template name and optional description + Save/Cancel button

**Section 3**
* "using format" dropdown with CSV and XLSX

**Section 4**
* "Download" button
   * If cartoon is selected in the table CSV should trigger an error
* Report field with summary (#64)

**Comment by ReneRanzinger** [comment]
![IMG_0887](https://github.com/glygener/glyTableMaker-backend/assets/2267640/4f28011f-0c82-4fd7-b377-129b2b5cb7a4)

**Comment by senaarpinar** [comment]
done
