### ISSUE TITLE
Add table maker column

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glyTableMaker-backend#63]
This is triggered from the table maker page (#62) and shows a dialog with:
* "Name"
  * Freely chosen by the user and can not be empty
  * Will be used as table heading the final table
* (Optional) Selection metadata 
  * Tree control and
  * List of glycan elements
    * GlyTouCan ID
    * Cartoon
    * Mass
* (Optional) Type
  * If glycan element is selected this field is disabled, otherwise
  * Dropdown with (Value, URI, ID)
  * Default Value
* Save/Cancel

**Comment by senaarpinar** [comment]
done
