### ISSUE TITLE
Download report

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glyTableMaker-backend#64]
When the download button in #62 is used the file should be created and downloaded (new tab). The report message should be:
* "Table creation successful" (Bold)
* bullet point list of warnings, e.g. one of the collections did not have metadata for a certain column -> column left empty

If the process failed a message is shown:
* "Table creation failed" (Bold) 
* bullet point list with reasons, e.g. for type ID was selected but the metadata did not have an ID

**Comment by senaarpinar** [comment]
done
