### ISSUE TITLE
Sign up page issues

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glyTableMaker-backend#7]
* increase password max length to 30
* The website accepts "a:/". It should make sure to start with "http://" or "https://" followed by characters, "." or "/" 
* If the passwords do not match there is no error but signup does nothing
* Trying to use an existing user name + Tab = Ops something went wrong
* Trying to use an existing email + Sign up = Ops something went wrong

**Comment by senaarpinar** [comment]
we were using react-bootstrap's form validation for URLs but changed the patters to accept only http(s).
The other issues are handled as well.

**Comment by ReneRanzinger** [comment]
The problem with the URL pattern is still there.

**Comment by senaarpinar** [comment]
fixed the URL pattern
