### ISSUE TITLE
GlyGen Metadata upload

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glyTableMaker-backend#77]
As discussed in our meeting with @Mindyporterfield we should have an easy way to add GlyGen metadata to a collection.

1. Add a button "Add GlyGen metadata" button left of the add metadata button in edit collection (above the metadata table).
2. That button brings you to the "second" page of the metadata wizard with all the GlyGen metadata shown by default with their corresponding input fields. Metadata that has a multiple attribute have a "+" icon on the right that allows to add one more "row" of the same metadata. Non-mandatory rows or additional rows (even for mandatory rows) have a trash bin icon to delete the row.

In the following listing mandatory rows a in bold:
* Evidence
* **Species**
* Strain
* Tissue
* Cell line ID
* Disease
* Glycan dictionary term ID
* **has_abundance**
* **has_expression**
* Functional annotation/Keyword
* Variant (Fly, yeast, mouse)
* Organismal/cellular Phenotype
* Molecular Phenotype
* **Contributor**
* Comment
* **Experimental technique** 

**_Please note_**: This listing makes assumptions:
* we only take _biological data_. Therefore species is required. If we allow to upload synthetic glycans that would have to be revised.
* we only take data resulting from _experiments_. If we allow to upload  theoretical glycans that would have to be revised.
* we do allow upload of _unpublished data_. Therefore Evidence (PMID or DOID) is not required.

**Comment by ReneRanzinger** [comment]
@jeet-vora will review the second part and confirm or suggest changes as part of #78

**Comment by senaarpinar** [comment]
implemented with the current mandatory selections.
