### ISSUE TITLE
Change password page

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glyTableMaker-backend#9]
* Spacing between input fields similar to login page.
* If I enter invalid information the "eye" icon shifts outside the input box
* Why not use the same error display strategy as on signup page?

**Comment by senaarpinar** [comment]
changed and make Signup and changePassword use same error handling mechanism

**Comment by ReneRanzinger** [comment]
https://glygen.ccrc.uga.edu/tablemaker/changePassword

is now a dead link.

**Comment by ReneRanzinger** [comment]
Its accessible now. But the question with the error report is still open. For signup page (and I thought for forced password reset as well) it shows the errors on the field rather than on top below the headline.

**Comment by senaarpinar** [comment]
changed the password error message to show on the field. But the errors concerning multiple fields and errors coming from the server are displayed on top
