### ISSUE TITLE
Export of Glycoprotein data

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glyTableMaker-backend#93]
GlycoProtein datasets should be exported according to the following example CSV:

[glycoprotein.csv](https://github.com/user-attachments/files/17347457/glycoprotein.csv)

**Comment by senaarpinar** [comment]
@ReneRanzinger How are we supposed to flatten out a glycoprotein with multiple sites/multiple glycans?
I assume we need to have a separate row for each site (of the protein) but how about for each glycan?

**Comment by senaarpinar** [comment]
done
